feat: creator-page
torin-asakura/VSBLE pull request #16
Opened 2022-04-06 16:30 UTC by brusselboy

2022-04-06 16:40 UTC, TFK70 requested changes
Помимо прочего - все месседжи нужно описывать в entrypoints/renderer/locales, у тебя их нет

2022-04-06 16:40 UTC, TFK70 commented on site/fragments/profile-info/src/user-details/user-details.component.tsx
> +          <FormattedMessage id='name.name' defaultMessage='Annija Abzalone' />
id у месседжа некорректный, они не так формируются

маска: `скоуп.идентификатор`, скоуп - это как правило название пакета, где используется месседж. В твоем случае `creator_page`

2022-04-06 16:40 UTC, TFK70 commented on site/fragments/profile-info/src/user-details/user-details.component.tsx
> +          <FormattedMessage id='residence.residence' defaultMessage='Cēsis, Cēsu pilsēta, Latvia' />
И из реквеста выше следует, что у тебя не может быть разных скоупов у месседжей в одном пакете

2022-04-06 16:40 UTC, TFK70 commented on site/fragments/profile-info/src/user-details/user-details.component.tsx
> +            www.luciaceldran.com
Для этого у тебя должны быть моки. На проекте есть как минимум два примера того, как их нужно организовывать

2022-04-06 16:40 UTC, TFK70 commented on site/fragments/public-info/src/about-me/about-me.component.tsx
> +              defaultMessage: 'Brief description for your profiles-page. URLs are hyperlinked.',
ээ?...

2022-04-06 16:40 UTC, TFK70 commented on ui/avatar/src/menu/menu.component.tsx
> +        path: '/profiles-page/settings',
???? 
ты зачем это сделал?

2022-04-06 16:40 UTC, TFK70 commented on ui/icons/src/InstagramInvertedIcon.tsx
> -
добавь ui/icons в .gitignore

2022-04-06 16:42 UTC, TFK70 commented on ui/icons/src/InstagramInvertedIcon.tsx
> -
@brusselboy после того как добавишь - делай git rm -rf чтобы из репы ui/icons/src вычистить

2022-04-12 17:29 UTC, TFK70 approved these changes

2022-04-12 20:25 UTC, TorinAsakura approved these changes
@brusselboy молодец

2022-04-12 20:25 UTC, TorinAsakura commented on ui/icons/src/LinkedinIcon.tsx
> +      <rect width={32} height={32} rx={16} fill='black' />
вы создали дубликат иконки в котором единственным отличием от inverted является props fill? Серьёзно?

2022-04-12 20:25 UTC, merged